### ISSUE TITLE
Image Fallback when preview image is not available

### ISSUE THREAD

**Issue by reginaldBarnabas** [winhtaikaung/react-tiny-link#13]
Is it possible to set a fallback preview image if image is not available instead of showing a blank image

**Comment by winhtaikaung** [comment]
Currently its not supported ,but  I have a plan for it and will added in next version

**Comment by reginaldBarnabas** [comment]
Thanks for your reply. When can we expect the next version. thanks in advance.

**Comment by winhtaikaung** [comment]
I m working on it so it should be available by next week.
