### ISSUE TITLE
I sometimes don't get metadata.

### ISSUE THREAD

**Issue by AllinGaming** [winhtaikaung/react-tiny-link#17]
sometimes everything is shown but sometime there is nothing https://media.discordapp.net/attachments/611152291189489695/611197210968981514/unknown.png?width=704&height=439

**Comment by winhtaikaung** [comment]
Yes it might be the proxy url error as we use `cors-anywhere` as default. So it depends on availability of proxy server. Can you try it by spinning up `https://github.com/Rob--W/cors-anywhere/` on your server and try it again ?

**Comment by AllinGaming** [comment]
Yes that was my thought first also. I will do this later on in the day and inform you to close the issue! Thank you for the quick response

**Comment by AllinGaming** [comment]
Works great! Thank you for your time. Great work. Have a nice day :)

**Comment by AllinGaming** [comment]
Hey man, I'm looking at your code and I don't understand why do you not create a link from og: tags on youtube but you do for Instagram? That's why I sometimes don't get the tags, can I pull and try to fix it up?

**Comment by winhtaikaung** [comment]
Sure man please feel free to send MR

**Comment by AllinGaming** [comment]
I want to ask you is it okay if we use these        
            <meta property="og:url" content="https://www.youtube.com/watch?v=MF9O33-WICs">
            <meta property="og:title" content="Minecraft movie Nederlands ABOVE">
            <meta property="og:image" content="https://i.ytimg.com/vi/MF9O33-WICs/maxresdefault.jpg">
            <meta property="og:description" content="♥ Steun ons kanaal! https://www.youtube.com/channel/UClqrIsr4kisG0bbP51NsGnQ Hey, Wij zijn YouY en we hebben met ons team een jaar lang aan deze minecraft fi...">

**Comment by AllinGaming** [comment]
Is it okay to use these for youtube?
`
<meta property="og:url" content="https://www.youtube.com/watch?v=MF9O33-WICs">
            <meta property="og:title" content="Minecraft movie Nederlands ABOVE">
            <meta property="og:image" content="https://i.ytimg.com/vi/MF9O33-WICs/maxresdefault.jpg">
            <meta property="og:description" content="♥ Steun ons kanaal! https://www.youtube.com/channel/UClqrIsr4kisG0bbP51NsGnQ Hey, Wij zijn YouY en we hebben met ons team een jaar lang aan deze minecraft fi...">`

**Comment by winhtaikaung** [comment]
For Description and title ?

**Comment by AllinGaming** [comment]
yes and also the image?

**Comment by winhtaikaung** [comment]
I found the issue as Youtube blocks our proxy at sometimes then the issue that we cannot scrape the title.

<img width="1037" alt="Screenshot 2019-08-20 at 6 46 06 PM" src="https://user-images.githubusercontent.com/6395793/63341070-f972fd80-c37a-11e9-9611-908c38d9dd50.png">

<img width="1035" alt="Screenshot 2019-08-20 at 6 46 14 PM" src="https://user-images.githubusercontent.com/6395793/63341071-fbd55780-c37a-11e9-8a77-bb0fd5d980fe.png">

**Comment by AllinGaming** [comment]
no, that's new, i use my own proxy it doesn't work i use postman to see the request and the return is good. I made a pull request can you check it out and fix if something is wrong?

**Comment by AllinGaming** [comment]
https://pledgr-cors-test.herokuapp.com try this as your test url

**Comment by winhtaikaung** [comment]
Close issue lack of activity. Please feel free to open it again :)

**Comment by jaypeetancero** [comment]
> https://pledgr-cors-test.herokuapp.com try this as your proxy url

Is it okay for me to use this proxy server?
