### ISSUE TITLE
react-tiny-link not supporting in IE Edge

### ISSUE THREAD

**Issue by gopinath-sixt** [winhtaikaung/react-tiny-link#25]
This is Good library. This library support in IE Edge? because the content not getting loaded in IE Edge.

**Comment by winhtaikaung** [comment]
Hi @gopinath-sixt 
To be honest ,I havent tested with IE Edge, will tested and get back to you

**Comment by winhtaikaung** [comment]
Hi @gopinath-sixt 
I've tested with IE,edge on my Mac, 

It renders normally

<img width="1663" alt="Screenshot 2019-11-20 at 2 14 55 PM" src="https://user-images.githubusercontent.com/6395793/69214287-793e7d00-0ba1-11ea-98cc-8e402cc48fe8.png">

**Comment by gopinath-sixt** [comment]
Hi @winhtaikaung 
Thanks for testing. 

I have tested from Window IEedge, It was rendering like i have attached. Mostly medium, instagram,facebook rendering like this.

![image](https://user-images.githubusercontent.com/23211334/69227546-45a02a80-0b82-11ea-9f02-b659e2f385c1.png)

**Comment by winhtaikaung** [comment]
Yes it might be the proxy url error as we use cors-anywhere as default. So it depends on availability of proxy server. Can you try it by spinning up https://github.com/Rob--W/cors-anywhere/ on your server and try it again ?

```jsx

import { ReactTinyLink } from 'react-tiny-link'

<ReactTinyLink
  cardSize="small"
  showGraphic={true}
  maxLine={2}
  minLine={1}
  url="https://www.amazon.com/Steve-Madden-Mens-Jagwar-10-5/dp/B016X44MKA/ref=lp_18637582011_1_1?srs=18637582011&ie=UTF8&qid=1550721409&sr=8-1"
proxyUrl="Your Proxy url "
/>
```

**Comment by gopinath-sixt** [comment]
Hi @winhtaikaung,
Now we are fetching the data via our server cors, response getting perfectly in IE edge but the content not getting rendered in IEEdge. 
![image](https://user-images.githubusercontent.com/23211334/69552290-7fb46680-0f9e-11ea-83c5-fb0a7aa202ee.png)

Do I need to update anything for IE Edge?

Env:
react: 18.6.0
react-dom: 18.6.0
react-tiny-link: 2.0.0
IE Edge: 44.18362.449.0
