### ISSUE TITLE
Proxy doesn't work in production

### ISSUE THREAD

**Issue by lukeberry99** [winhtaikaung/react-tiny-link#30]
The proxy doesn't work after `npm run build` but does work when running `npm run start` - we've tried setting it explicitly 

```javascript
return <ReactTinyLink
  cardSize="small"
  showGraphic={ true }
  maxLine={ 2 }
  minLine={ 1 }
  url={ link }
  proxyUrl="https://cors-anywhere.herokuapp.com"
/>
```

As well as leaving it as the default, and it doesn't work in either configuration.

Cheers for the help

**Comment by winhtaikaung** [comment]
Hi @lukeberry99 
Appreciated for opening issue. 
I will look into it

**Comment by winhtaikaung** [comment]
Hope the issue has been resolved,Please feel free to reopen if any issue comes up.
