### ISSUE TITLE
Some demo examples not working

### ISSUE THREAD

**Issue by kratoskat** [winhtaikaung/react-tiny-link#37]
Hello and thanks for this module!

Looking at the demo, it seems like the Amazon and mp3 example aren't working and i'm also getting the same issue when i used it. Any idea what's wrong?

thanks

**Comment by winhtaikaung** [comment]
Hi @kratoskat 
Because the default proxy server got issue to read the link? eg. it might get blocked
Can you try to change the proxyURL to your own proxyUrl?
you may want to clone

https://github.com/Rob--W/cors-anywhere

and host it on your own and pass the hosted proxyURL and try it again ?

**Comment by kratoskat** [comment]
Hey, thanks for the reply. I've updated some components in my app and it started working. I'm not using the proxy at all.
