### ISSUE TITLE
EBADPLATFORM - Not able to install react-tiny-link in windows

### ISSUE THREAD

**Issue by kyasamadhavi** [winhtaikaung/react-tiny-link#39]
Issue occur while 'npm install save react-tiny-link' and gives me below error .
unsupported platform for node-win-x86@11.15.0: wanted {os:win32,arch:x86}  (current: {os:win32,arch:ia32}

**Comment by winhtaikaung** [comment]
Hope the issue has resolved. Pleaes feel free to open if you have any issue
