### ISSUE TITLE
Show only the image without descriptions

### ISSUE THREAD

**Issue by caraquista** [winhtaikaung/react-tiny-link#42]
Hey.... nice work....first of all congratulations.....

I write because i have an array of links and need to show in a list but only the image... is tthis posible with your library??

waiting a fast response.

**Comment by winhtaikaung** [comment]
Hi @caraquista  I think this is out of our scope as the purpose of the component is to provide preview with links. Sorry for your inconvenience. :bowing_man:

**Comment by caraquista** [comment]
But if you can view only the description of the link with showGraphic={true} configuration, why we cannot see only the image without description, something like showDescription={false}
