### ISSUE TITLE
Warning: Received `false` for a non-boolean attribute `loading`.

### ISSUE THREAD

**Issue by nastikue** [winhtaikaung/react-tiny-link#47]
Console warning appears in the project when adding ReactTinyLink:
![image](https://user-images.githubusercontent.com/13137535/78462409-48875c00-76da-11ea-8246-5ee0bc334a7b.png)

Use case: create clean react project (npx create-react-app my-app), insert in App.js:
<ReactTinyLink
          cardSize="small"
          showGraphic
          maxLine={2}
          minLine={1}
          url="https://reactjs.org"
          />
![image](https://user-images.githubusercontent.com/13137535/78462438-91d7ab80-76da-11ea-8853-30e28904409c.png)

**Comment by winhtaikaung** [comment]
@all-contributors please add @nastikue for bug
