### ISSUE TITLE
Preview of a Twitter page doesn't show correctly

### ISSUE THREAD

**Issue by think-in-universe** [winhtaikaung/react-tiny-link#62]
Thanks for your awesome work of building this package. Here is an issue about Twitter. 

### Description

Preview the link `https://twitter.com/linuxfoundation/status/1257347380728512513` in the demo page, but no image and title are rendered.

![image](https://user-images.githubusercontent.com/46699230/81096599-3860d780-8f39-11ea-981e-ddc13cd5965d.png)

### Analysis

In the demo, the fetched html via `https://cors-anywhere.herokuapp.com/https://twitter.com/linuxfoundation/status/1257347380728512513` xhr, doesn't contain the title and image meta info. A site level html template will be returned. 

If we visit twitter via either the original url `https://twitter.com/linuxfoundation/status/1257347380728512513` in a separate browser tab or via curl, or we access `https://cors-anywhere.herokuapp.com/https://twitter.com/linuxfoundation/status/1257347380728512513` via curl in command line and set user-agent to empty, we'll retrieve the html page with the both title and image meta. 

### Question

Have you tested Twitter links before? What's the recommended solution to resolve this issue?

**Comment by stuckinaboot** [comment]
Having the same issue. I also noticed on the React Tiny Link demo (and on my website) that Instagram links don't seem to have an image preview anymore. Huge fan of the component by the way.

**Comment by winhtaikaung** [comment]
> Thanks for your awesome work of building this package. Here is an issue about Twitter.
> 
> ### Description
> Preview the link `https://twitter.com/linuxfoundation/status/1257347380728512513` in the demo page, but no image and title are rendered.
> 
> ![image](https://user-images.githubusercontent.com/46699230/81096599-3860d780-8f39-11ea-981e-ddc13cd5965d.png)
> 
> ### Analysis
> In the demo, the fetched html via `https://cors-anywhere.herokuapp.com/https://twitter.com/linuxfoundation/status/1257347380728512513` xhr, doesn't contain the title and image meta info. A site level html template will be returned.
> 
> If we visit twitter via either the original url `https://twitter.com/linuxfoundation/status/1257347380728512513` in a separate browser tab or via curl, or we access `https://cors-anywhere.herokuapp.com/https://twitter.com/linuxfoundation/status/1257347380728512513` via curl in command line and set user-agent to empty, we'll retrieve the html page with the both title and image meta.
> 
> ### Question
> Have you tested Twitter links before? What's the recommended solution to resolve this issue?

Hey @think-in-universe I think I may have to add twitter specific scraper for this issue , Sorry for inconvenience. I will mark this as enhancement and will be updated when next version release.

![image](https://user-images.githubusercontent.com/6395793/81882379-a00dc700-95b8-11ea-9ce5-3fd7f458e957.png)

## Twitter  response

https://pastebin.pl/view/79829d74

**Comment by winhtaikaung** [comment]
> Having the same issue. I also noticed on the React Tiny Link demo (and on my website) that Instagram links don't seem to have an image preview anymore. Huge fan of the component by the way.

Hi @stuckinaboot  Sorry to hear that, Could you please help me to reproduce your error with codesandbox?

**Comment by think-in-universe** [comment]
@winhtaikaung thanks a lot. 
looking forward to the next release.

**Comment by stuckinaboot** [comment]
@winhtaikaung tried reproducing in codesandbox (https://codesandbox.io/s/monp6n08n8?fontsize=14&file=/src/index.js) but the issue for Instagram seems to be resolved. Thanks!

**Comment by sndsabin** [comment]
> ### Analysis
> In the demo, the fetched html via `https://cors-anywhere.herokuapp.com/https://twitter.com/linuxfoundation/status/1257347380728512513` xhr, doesn't contain the title and image meta info. A site level html template will be returned.
> 
> If we visit twitter via either the original url `https://twitter.com/linuxfoundation/status/1257347380728512513` in a separate browser tab or via curl, or we access `https://cors-anywhere.herokuapp.com/https://twitter.com/linuxfoundation/status/1257347380728512513` via curl in command line and set user-agent to empty, we'll retrieve the html page with the both title and image meta.

Hey @winhtaikaung , The issue seems to be as stated by @think-in-universe in Analysis. I deployed `cors-anywhere` by overriding the `User-Agent` request header, used it as `proxyUrl` and that seems to work without adding twitter specific scraper. Seems as we need to deploy `cors-proxy` by overriding the `User-Agent` for this specific library and set it to default instead of using `https://cors-anywhere.herokuapp.com/` as default. The link to sandbox is below:

https://codesandbox.io/s/react-tiny-link-5cpuv?file=/src/index.js 

**Can we address this issue without using our own proxy ?**

seems like in firefox, we could override the `User-Agent` request header but in chrome we can't. 

P.S. If you wish to add twitter specific scrapper anyway, would be happy to open a PR (https://github.com/sndsabin/react-tiny-link/tree/add-twitter-scrapper)

**Comment by winhtaikaung** [comment]
> > ### Analysis
> > In the demo, the fetched html via `https://cors-anywhere.herokuapp.com/https://twitter.com/linuxfoundation/status/1257347380728512513` xhr, doesn't contain the title and image meta info. A site level html template will be returned.
> > If we visit twitter via either the original url `https://twitter.com/linuxfoundation/status/1257347380728512513` in a separate browser tab or via curl, or we access `https://cors-anywhere.herokuapp.com/https://twitter.com/linuxfoundation/status/1257347380728512513` via curl in command line and set user-agent to empty, we'll retrieve the html page with the both title and image meta.
> 
> Hey @winhtaikaung , The issue seems to be as stated by @think-in-universe in Analysis. I deployed `cors-anywhere` by overriding the `User-Agent` request header, used it as `proxyUrl` and that seems to work without adding twitter specific scraper. Seems as we need to deploy `cors-proxy` by overriding the `User-Agent` for this specific library and set it to default instead of using `https://cors-anywhere.herokuapp.com/` as default. The link to sandbox is below:
> 
> https://codesandbox.io/s/react-tiny-link-5cpuv?file=/src/index.js
> 
> **Can we address this issue without using our own proxy ?**
> 
> seems like in firefox, we could override the `User-Agent` request header but in chrome we can't.
> 
> **P.S.** If you wish to add twitter specific scrapper anyway, a PR (#64) is open for same.

As for me since our component will render in different browsers, I would love to have separate scrapper for twitter.

**Comment by winhtaikaung** [comment]
Hi @think-in-universe  I think the latest version got twitter support so I will close that issue now. Please feel free to reopen issue if you still have that issue.

**Comment by think-in-universe** [comment]
@winhtaikaung cool. thanks. I'll have a try and let you know for any issues 😄
