### ISSUE TITLE
TypeError: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by NicholasIoanJones** [winhtaikaung/react-tiny-link#72]
We are trying to render link previews from user input data which means that text which looks like URLs may end up being invalid. 
Can this be made more fault tolerant?

Stack below:
t.getHostname
src/utils.ts:20
  17 | 
  18 | export const getHostname = href => {
  19 |   const { hostname } = new URL(href);
> 20 |   return hostname.replace(REGEX_STRIP_WWW, '');
  21 | };
  22 | 
  23 | export const isLarge = cardSize => cardSize === 'large';
View compiled
t.ReactTinyLink
src/ReactTinyLink.tsx:55
  52 |   </Description>
  53 | </Content>
  54 | <Footer className="react_tinylink_footer">
> 55 |   <Description loading={loading} loadingWidth={1} className="react_tinylink_card_footer_description">
     | ^  56 |     {getHostname(url)}
  57 |   </Description>
  58 | </Footer>
View compiled

**Comment by winhtaikaung** [comment]
Hi @NicholasIoanJones it is possible as we have props called `defaultMedia` that you can put the default media if the component failed to fetch the metadata.
Ref: https://github.com/winhtaikaung/react-tiny-link#props--methods

**Comment by winhtaikaung** [comment]
Hope the issue has resolved, Please feel free to reopen
