### ISSUE TITLE
gatsby support

### ISSUE THREAD

**Issue by seonglae** [winhtaikaung/react-tiny-link#73]
![image](https://user-images.githubusercontent.com/27716524/86486762-2499ec00-bd97-11ea-9110-b4a7c04253f5.png)

I can't embed this component in my gatsby app
I just import this component and rendered it

**Comment by winhtaikaung** [comment]
Thanks for opening issue @sungle3737 .
We are working on removing React DOM version of react-tiny-link. Will keep it as bug report.

**Comment by winhtaikaung** [comment]
Hello @sungle3737 , Thanks for reporting that issue , I 've moved the react & react-dom to peerdependencies. 
Once the #75  was published by next week you may try it again.

**Comment by sungle3737** [comment]
I think still not published, when is the plan?

**Comment by winhtaikaung** [comment]
Its released @sungle3737

**Comment by sungle3737** [comment]
```bash
 WebpackError: ReferenceError: window is not defined

  - index.js:1 Object../node_modules/react-tiny-link/lib/index.js
    node_modules/react-tiny-link/lib/index.js:1:371

  - cards.js:1 Module../src/components/paral/Third/cards.js
    src/components/paral/Third/cards.js:1:1

  - index.js:1 Module../src/components/paral/index.js
    src/components/paral/index.js:1:1

  - index.js:1 Module../src/pages/index.js
    src/pages/index.js:1:1
```

It can served, but it cannot be build

**Comment by rosnovsky** [comment]
Hey @winhtaikaung! Thank you for this nice package!

`WebpackError: ReferenceError: window is not defined` is still happening: Gatsby can serve this in dev mode but is unable to build it. The `window` is indeed not available when server-rendering pages with `react-tiny-link`. The only reference to `window` I could find is in the `serviceWorker.js`:

https://github.com/winhtaikaung/react-tiny-link/blob/master/src/serviceWorker.ts#L14

Is it something that absolutely has to be present? Is it possible to remove this `serviceWorker` entirely?

**Comment by gentksb** [comment]
I want this issue be fixed too.

**Comment by winhtaikaung** [comment]
@gentksb Seems like GatsBy uses `ssr`. 
Please refer to updated [README.md](https://github.com/winhtaikaung/react-tiny-link#nextjs) for Next.js support. :pray:. I will close the ticket for now. Please feel free to open again if you need assistance.
