### ISSUE TITLE
Bundle size & duplicate react-dom.production 

### ISSUE THREAD

**Issue by anuraghazra** [winhtaikaung/react-tiny-link#74]
Hi, thank you for the amazing lib. it works super nicely. 

but i only have one issue with it, is that the bundle size is too large.. i don't know if something is wrong or i'm doing something wrong the size is around 190kb and it also includes react-dom.production for some reason. 

![image](https://user-images.githubusercontent.com/35374649/86528073-63789080-bec2-11ea-8338-ce87de892550.png)

**Comment by winhtaikaung** [comment]
Hello @anuraghazra, Thanks for reporting that issue , I 've moved the react & react-dom to peerdependencies. 
Once the #75  was published by next week you may try it again.

**Comment by anuraghazra** [comment]
Hi @winhtaikaung thanks for the swift response and fix. 

Btw it also uses the styled-components right? so i think it should also be moved to peerdependencies?

because looking at my bundle analyzer i think i also have duplicate styled-component.

**Comment by winhtaikaung** [comment]
> Hi @winhtaikaung thanks for the swift response and fix.
> 
> Btw it also uses the styled-components right? so i think it should also be moved to peerdependencies?
> 
> because looking at my bundle analyzer i think i also have duplicate styled-component.

:thinking: Ok I put it as  some project might not use styled-components. Let me check
