### ISSUE TITLE
feature request: provide a custom hook for grabbing link meta data

### ISSUE THREAD

**Issue by anuraghazra** [winhtaikaung/react-tiny-link#77]
- Issue type: feature request

- Description: 
Hi, i was just looking at the source and i thought it would be pretty neat if we have some sort of custom hook for just fetching the URL meta data.  
I noticed you have a `useMountFetch` hook and i think it will just work fine.
Renaming & exporting it to something like `useScrapper` or `useScrapeData` would be sufficient i think. 

- Use cases 
Users will have more flexibility and can style the data or use their own custom components. 
If we leverage treeshaking then we don't have to bundle the react-tiny-link specific components.
It will also solve issues for example if a project does not have styled-component then their project won't have it. and users would create their own custom components with the useScrapper hook
might also solve #35 in some regards.

**Comment by winhtaikaung** [comment]
Hope this issue has been resolved by @kalimantos. I will close this issue for now . Please feel free to reopen if you have any.
