### ISSUE TITLE
when putting an url without http:// it crashes

### ISSUE THREAD

**Issue by handrei** [winhtaikaung/react-tiny-link#80]
hello, I'm using this library the latest version and when I tried to put a link without HTTP:// it crashed with error: `TypeError
Failed to construct 'URL': Invalid URL`
i also tried on the sandbox [](https://codesandbox.io/s/monp6n08n8?fontsize=14&file=/src/index.js) and it's with the same error

anyone had this issue?

**Comment by winhtaikaung** [comment]
its expected behavior so you may need to provide correct URL format.

**Comment by winhtaikaung** [comment]
I will close this issue @handrei  Please feel free to reopen new issue if you still facing the issue after using proper URL.
