### ISSUE TITLE
Nextjs support: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by PeerRich** [winhtaikaung/react-tiny-link#83]
I am getting this when using nextjs, in general, seems like SSR is not working so far.

![image](https://user-images.githubusercontent.com/8019099/93891959-e5b76a80-fce3-11ea-9cb4-70b0df9c1461.png)

**Comment by PeerRich** [comment]
I have tried this without success

```
const ReactTinyLink = dynamic(
    () => import('react-tiny-link'),
    {ssr: false}
    )
```

**Comment by edin228** [comment]
```
import dynamic from 'next/dynamic';

const ReactTinyLink = dynamic(
    () => import('react-tiny-link').then(mod => mod.ReactTinyLink),
    { ssr: false }
  )
```

this works for me

**Comment by luknl** [comment]
@edin228  any idea on how to make it work with the [Hook usage](https://github.com/winhtaikaung/react-tiny-link#hook-usage)?

**Comment by winhtaikaung** [comment]
Hi @edin228 really appreciate for your help.  Please refer to updated [README.md](https://github.com/winhtaikaung/react-tiny-link#nextjs) for Next.js support. :pray:. I will close the ticket for now. Please feel free to open again if you need assistance.

**Comment by ical10** [comment]
Hello. I encounter this problem inside my functional component, even when using what is mentioned in README.md for Next.js support.
My configuration: 
```
Next.js v9.5.5
react-tiny-link v3.6.1
```
Any leads are much appreciated, thanks!
