### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by LIJIOJOHN123** [winhtaikaung/react-tiny-link#97]
![image](https://user-images.githubusercontent.com/24985837/113001119-1fcf6080-918e-11eb-9abe-5f8e5c54ea54.png)

**Comment by winhtaikaung** [comment]
Hi @LIJIOJOHN123  Please refer to updated [README.md](https://github.com/winhtaikaung/react-tiny-link#nextjs) for Next.js support. :pray:. I will close the ticket for now. Please feel free to open again if you need assistance.
